OnlineShopping/Controllers/CartController.cs
using OnlineShopping.ServiceLayer;
using OnlineShopping.ViewModel;
using System;///to handle exception
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnlineShopping.Controllers
{
    /// <summary>
    /// This controller handles cart funtionalities;
    /// Stores the products added to cart in session untill the user is logging in and
    ///adds to the cart db only when the user on successful sign-in.
    ///The user can remove the cart products; increase or decrease the product quantity in the cart.
    /// </summary>

    [AllowAnonymous]
    public class CartController : Controller
    {
        CartServices cartServices = new CartServices();

        //if authenticated user adds to cart, this will store the products in cart db
        //if the user is un authenticated, it will simply maintain cart items in session variable.
        public ActionResult AddToCart(int id)
        {
            try
            {
                ProductViewModel productViewModel = cartServices.GetProduct(id);
                List<CartViewModel> cartViewModels = new List<CartViewModel>();
                if (Session["uname"] == null)
                {
                    if (Session["CartItems"] != null)
                    {
                        cartViewModels = Session["CartItems"] as List<CartViewModel>;
                        cartViewModels = cartServices.AddToList(cartViewModels, productViewModel);
                    }
                    else
                    {

                        cartViewModels = cartServices.AddToList(cartViewModels, productViewModel);
                    }
                    Session["CartCounter"] = cartViewModels.Count;
                    Session["CartItems"] = cartViewModels;
                    return RedirectToAction("ProductsList", "Product");
                }
                else
                {
                    cartServices.AddToDb(Session["uname"] as string, productViewModel);
                    return RedirectToAction("ProductsList", "Product");
                }
            }
            catch (Exception e)
            {
                return View("Error", new HandleErrorInfo(e, "ProductsList", "Product"));
            }

        }

        //This methods gets all the cart products either from session or from db
        //based on the authenticity of the user and displays them.
        public ActionResult ShowCart()
        {
            try
            {
                List<CartViewModel> cartViewModels = new List<CartViewModel>();

                if (Session["uname"] != null)
                {
                    cartViewModels = cartServices.ShowCartFromDb(Session["uname"] as string);
                    return View(cartViewModels);

                }
                if (Session["CartItems"] != null)
                {
                    List<CartViewModel> sessionCartViewModels = Session["CartItems"] as List<CartViewModel>;
                    foreach (var item in sessionCartViewModels)
                    {
                        cartViewModels.Add(item);
                    }

                }
                return View(cartViewModels);
            }
            catch (Exception e)
            {
                return View("Error", new HandleErrorInfo(e, "ProductsList", "Product"));
            }
        }

        //This would remove the selected product from session variable of cart items or,
        //from the db if the user is authenticated.
        [HttpPost]
        public ActionResult RemoveFromCart(int cartId, int productId)
        {
            List<CartViewModel> cartViewModels = Session["CartItems"] as List<CartViewModel>;
            Session["CartItems"] = cartServices.RemoveFromCart(cartViewModels, cartId, productId);
            Session["CartCounter"] = (Session["CartItems"] as List<CartViewModel>).Count;
            return RedirectToAction("ShowCart");

        }

        //This method is called upon clicking the increase quantity button in the cart page 
        //to increase the quantity by one for each click.
        [HttpPost]
        public ActionResult IncreaseQuantity(int cartId, int productId)
        {
            Session["CartItems"] = cartServices.IncreaseQuantity(Session["CartItems"] as List<CartViewModel>, cartId, productId);
            return RedirectToAction("ShowCart");
        }

        //This method is called upon clicking the increase quantity button in the cart page 
        //to increase the quantity by one for each click.
        [HttpPost]
        public ActionResult DecreaseQuantity(int cartId, int productId)
        {
            Session["CartItems"] = cartServices.DecreaseQuantity(Session["CartItems"] as List<CartViewModel>, cartId, productId);
            return RedirectToAction("ShowCart");
        }
    }
}

OnlineShopping/Controllers/SharedController.cs
using System;
using System.IO;
using System.Web.Mvc;

namespace OnlineShopping.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];
                //Changes the name of the images uploaded by the user
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

OnlineShopping/Controllers/ShoppingController.cs
using OnlineShopping.DomainLayer;
using OnlineShopping.ServiceLayer;
using OnlineShopping.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace OnlineShopping.Controllers
{
    /// <summary>
    /// This handles customer side functionalities.
    /// User has the option to buy a single product as well as to buy multiple products stored in their cart at once.
    /// User can view their already bought products;currently placed orders;
    /// Make request to cancel their order; on checkout, they are directed to checkout page,
    /// where they fill out their details and they can also increase or decrease product quantity there.
    /// On successfully placing order, request will be sent to admin for further processing.
    /// </summary>
    public class ShoppingController : Controller
    {
        ShoppingServices shoppingServices;
        UserServices userServices;
        CheckoutViewModel checkoutViewModel = new CheckoutViewModel();

        public ShoppingController()
        {
            shoppingServices = new ShoppingServices();
            userServices = new UserServices();
        }

        //Shows checkout page where user views their detals and products details.
        [Authorize(Roles = "Customer")]
        public ActionResult Checkout(int? productId)
        {
            string username = Session["uname"] as string;
            if (productId == null)
            {
                checkoutViewModel.CartViewModel = shoppingServices.GetUserProducts(username);
            }
            else
            {
                checkoutViewModel.CartViewModel = shoppingServices.GetUserProduct(Convert.ToInt32(productId));
            }
            checkoutViewModel.UserViewModel = userServices.Detail(username);
            Session["CheckoutItems"] = checkoutViewModel.CartViewModel.ToList();
            Session["PlaceOrder"] = checkoutViewModel;
            return RedirectToAction("ShowCheckoutPage");
        }

        //This method is called upon clicking the increase quantity button in the checkout page 
        //to increase the quantity by one for each click.
        [HttpPost]
        public ActionResult IncreaseQuantity(int productId)
        {
            Session["CheckoutItems"] = shoppingServices.IncreaseQuantity(Session["CheckoutItems"] as List<CartViewModel>, productId);
            return RedirectToAction("ShowCheckoutPage");
        }

        //This method is called upon clicking the decrease quantity button in the cart page 
        //to decrease the quantity by one for each click.
        [HttpPost]
        public ActionResult DecreaseQuantity(int productId)
        {
            Session["CheckoutItems"] = shoppingServices.DecreaseQuantity(Session["CheckoutItems"] as List<CartViewModel>, productId);
            return RedirectToAction("ShowCheckoutPage");
        }
        public ActionResult ShowCheckoutPage()
        {
            string username = Session["uname"] as string;
            checkoutViewModel.CartViewModel = Session["CheckoutItems"] as List<CartViewModel>;
            checkoutViewModel.UserViewModel = userServices.Detail(username);
            Session["PlaceOrder"] = checkoutViewModel;
            return View(checkoutViewModel);
        }
        public ActionResult PlaceOrder(decimal totalAmount)
        {
            checkoutViewModel = Session["PlaceOrder"] as CheckoutViewModel;
            shoppingServices.PlaceOrder(checkoutViewModel, totalAmount);
            shoppingServices.RemoveCartproducts(checkoutViewModel.CartViewModel);
            return RedirectToAction("ProductsList", "Product");
        }

        //Gets curent user from session variable and display their orders from the orders db.
        public ActionResult YourOrders()
        {
            List<OrderViewModel> orderViewModels = shoppingServices.GetYourOrders(Session["uname"] as string);
            return View(orderViewModels);
        }

        //Gets orderId and shows detail of the same.
        public ActionResult YourOrderDetails(int? orderId)
        {
            if (orderId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "There is some problem.");
            }
            else
            {
                List<OrderDetail> orderDetails = shoppingServices.GetYourOrderDetails(Convert.ToInt32(orderId));
                return View(orderDetails);
            }
        }

        //Gets current user from session variable and shows their previously bought items from the completedOrders db.
        public ActionResult YourOrdersHistory()
        {
            List<CompletedOrdersViewModel> completedOrdersViewModels = shoppingServices.YourOrdersHistory(Session["uname"] as string);
            return View(completedOrdersViewModels);
        }

        //This would send a cancel request for an order getting the orderId
        public ActionResult CancelOrder(int? orderId)
        {
            if (orderId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "There is some problem.");
            }
            else
            {
                shoppingServices.CancelOrder(Convert.ToInt32(orderId));
                return RedirectToAction("YourOrders");
            }
        }
    }
}

OnlineShopping/Controllers/UserController.cs
using OnlineShopping.DomainLayer;
using OnlineShopping.ServiceLayer;
using OnlineShopping.ViewModel;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace OnlineShopping.Controllers
{
    /// <summary>
    /// This handles user related functionalities.
    /// Admin and users can view thier profile and update the same; change their passwords;
    /// Admin can change user roles and view user details.
    /// </summary>

    public class UserController : Controller
    {
        UserServices userServices = new UserServices();
        [Authorize(Roles = "Admin")]
        public ActionResult UserDetails()
        {
            IEnumerable<UserViewModel> userViewModels = userServices.DisplayAll();
            return View(userViewModels);
        }
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserViewModel userViewModel = userServices.Detail(Convert.ToInt32(id));
            return View(userViewModel);
        }
        public ActionResult Edit(int userId)
        {
            IEnumerable<Role> Roles = userServices.GetRoles();
            ViewBag.Roles = new SelectList(Roles, "RoleId", "RoleName");

            UserViewModel userViewModel = userServices.Detail(userId);

            if (userViewModel == null)
            {
                return HttpNotFound();
            }
            return PartialView(userViewModel);

        }

        [HttpPost]
        public ActionResult Edit(UserViewModel userViewModel)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    IEnumerable<Role> Roles = userServices.GetRoles();
                    ViewBag.Roles = new SelectList(Roles, "RoleId", "RoleName");

                    userServices.Edit(userViewModel);

                    return RedirectToAction("UserDetails");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return View("Error", new HandleErrorInfo(e, "ProductsList", "Product"));
            }
        }
        //[HttpPost]
        //public ActionResult Delete(int userId)
        //{
        //    userServices.Delete(userId);
        //    return RedirectToAction("UserDetails");
        //}
        public ActionResult UpdateProfile()
        {
            UserViewModel userViewModel = userServices.Detail(Session["uname"] as string);
            return View(userViewModel);
        }
        [HttpPost]
        public ActionResult UpdateProfile(UserViewModel userViewModel)
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    userViewModel.RoleId = 1;
                }
                else
                {
                    userViewModel.RoleId = 2;
                }
                userServices.Edit(userViewModel);
                Session["uname"] = userViewModel.UserName.ToString();
                return RedirectToAction("Index", "Product");
            }
            catch (Exception e)
            {
                return View("Error", new HandleErrorInfo(e, "ProductsList", "Product"));
            }
        }

        public ActionResult ChangePassword()
        {
            UserViewModel userViewModel = userServices.Detail(Session["uname"] as string);
            return View(userViewModel);
        }
        [HttpPost]
        public ActionResult ChangePassword(UserViewModel userViewModel)
        {
            try
            {
                if (userViewModel.Password == userViewModel.OldPassword)
                {
                    userViewModel.Password = userViewModel.NewPassword;
                    userServices.Edit(userViewModel);
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect Old Password");
                    return View();
                }
            }
            catch (Exception e)
            {
                return View("Error", new HandleErrorInfo(e, "ProductsList", "Product"));
            }

        }
    }
}

OnlineShopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gratitude -Online Shopping</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <style>
        .dropbtn {
            background-color: #222;
            color: #9d9d9d;
            padding: 16px;
            font-size: 16px;
            border: none;
            font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            font-size: 14px;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f1f1f1;
            min-width: 1200px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #ddd;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        /*.dropdown:hover .dropbtn {
        background-color: #3e8e41;
        }*/
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gratitude", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Home")"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                    <li><a href="@Url.Action("ProductsList","Product")"><span class="glyphicon glyphicon-list-alt"></span> Products</a></li>
                   

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Convert.ToInt32(Session["CartCounter"]) > 0)
                    {
                        <li>@Html.ActionLink("Cart(" + Session["CartCounter"] + ")", "ShowCart", "Cart")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Cart", "ShowCart", "Cart")</li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <div class="dropdown">
                                <button class="dropbtn">
                                    <span class="glyphicon glyphicon-user "></span> Hi @Session["uname"]
                                </button>
                                <div class="dropdown-content">
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a href="@Url.Action("UserDetails","User")"><span class="glyphicon glyphicon-user"></span> Users</a>
                                        <a href="@Url.Action("ShowPendingOrders","Order")"><span class="glyphicon glyphicon-list"></span> Orders</a>
                                        <a href="@Url.Action("ShowCompletedOrders","Order")"><span class="glyphicon glyphicon-list"></span> Completed Orders</a>
                                        <a href="@Url.Action("CancelledOrders","Order")"><span class="glyphicon glyphicon-remove"></span> Cancelled Orders</a>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("YourOrders","Shopping")"><span class="glyphicon glyphicon-flag"></span> Your Orders</a>
                                        <a href="@Url.Action("YourOrdersHistory","Shopping")"><span class="glyphicon glyphicon-gift"></span> Your orders history</a>
                                    }

                                    <a href="@Url.Action("UpdateProfile","User")"><span class="glyphicon glyphicon-pencil"></span> Update Profile</a>
                                    <a href="@Url.Action("Logout","Account")"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                                </div>
                            </div>
                        </li>
                    }

                    else
                    {
                        <li><a href="@Url.Action("Login","Account")"><span class="glyphicon glyphicon-log-in"></span> Signin</a></li>
                    }

                </ul>

            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>